# Generated by Django 5.2.8 on 2025-11-13 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Grupo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Grupo de Máquinas',
                'verbose_name_plural': 'Grupos de Máquinas',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True, verbose_name='Hostname')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC Address')),
                ('os_version', models.CharField(blank=True, max_length=100, verbose_name='Versão do SO')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Última Conexão')),
                ('is_online', models.BooleanField(default=False, verbose_name='Online')),
                ('cpu', models.CharField(blank=True, max_length=200, verbose_name='CPU')),
                ('motherboard', models.CharField(blank=True, max_length=200, verbose_name='Placa-mãe')),
                ('ram_gb', models.IntegerField(blank=True, null=True, verbose_name='RAM (GB)')),
                ('disk_space_gb', models.IntegerField(blank=True, null=True, verbose_name='Disco Total (GB)')),
                ('disk_free_gb', models.IntegerField(blank=True, null=True, verbose_name='Disco Livre (GB)')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.machinegroup', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('sent_to_all', models.BooleanField(default=True, verbose_name='Enviar para todos')),
                ('groups', models.ManyToManyField(blank=True, to='inventory.machinegroup', verbose_name='Grupos')),
                ('machines', models.ManyToManyField(blank=True, to='inventory.machine', verbose_name='Máquinas Específicas')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
        migrations.CreateModel(
            name='BlockedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='URL Bloqueada')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.machine', verbose_name='Máquina')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.machinegroup', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Site Bloqueado',
                'verbose_name_plural': 'Sites Bloqueados',
                'unique_together': {('url', 'group'), ('url', 'machine')},
            },
        ),
    ]
