# Generated by Django 5.2.8 on 2025-11-14 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='motherboard',
        ),
        migrations.AddField(
            model_name='machine',
            name='antivirus_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Antivírus'),
        ),
        migrations.AddField(
            model_name='machine',
            name='av_state',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estado AV'),
        ),
        migrations.AddField(
            model_name='machine',
            name='bios_release',
            field=models.CharField(blank=True, max_length=50, verbose_name='Data BIOS'),
        ),
        migrations.AddField(
            model_name='machine',
            name='bios_version',
            field=models.CharField(blank=True, max_length=100, verbose_name='Versão BIOS'),
        ),
        migrations.AddField(
            model_name='machine',
            name='gpu_driver',
            field=models.CharField(blank=True, max_length=100, verbose_name='Driver Vídeo'),
        ),
        migrations.AddField(
            model_name='machine',
            name='gpu_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Placa de Vídeo'),
        ),
        migrations.AddField(
            model_name='machine',
            name='install_date',
            field=models.CharField(blank=True, max_length=30, verbose_name='Instalação SO'),
        ),
        migrations.AddField(
            model_name='machine',
            name='last_boot',
            field=models.CharField(blank=True, max_length=30, verbose_name='Último Boot'),
        ),
        migrations.AddField(
            model_name='machine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='machine',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='machine',
            name='network_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Adaptadores Rede'),
        ),
        migrations.AddField(
            model_name='machine',
            name='os_architecture',
            field=models.CharField(blank=True, max_length=50, verbose_name='Arquitetura SO'),
        ),
        migrations.AddField(
            model_name='machine',
            name='os_build',
            field=models.CharField(blank=True, max_length=20, verbose_name='Build SO'),
        ),
        migrations.AddField(
            model_name='machine',
            name='os_caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='SO Caption'),
        ),
        migrations.AddField(
            model_name='machine',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Serial BIOS'),
        ),
        migrations.AddField(
            model_name='machine',
            name='uptime_days',
            field=models.FloatField(blank=True, null=True, verbose_name='Uptime (dias)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='disk_free_gb',
            field=models.FloatField(blank=True, null=True, verbose_name='Disco Livre (GB)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='disk_space_gb',
            field=models.FloatField(blank=True, null=True, verbose_name='Disco Total (GB)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.machinegroup'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='ram_gb',
            field=models.FloatField(blank=True, null=True, verbose_name='RAM (GB)'),
        ),
    ]
