# Generated by Django 5.2.8 on 2025-11-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_machine_motherboard_machine_antivirus_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='memory_modules',
            field=models.JSONField(blank=True, null=True, verbose_name='Módulos de Memória'),
        ),
        migrations.AddField(
            model_name='machine',
            name='populated_memory_slots',
            field=models.IntegerField(blank=True, null=True, verbose_name='Slots Ocupados'),
        ),
        migrations.AddField(
            model_name='machine',
            name='total_memory_slots',
            field=models.IntegerField(blank=True, null=True, verbose_name='Slots Totais'),
        ),
    ]
